const { Equipment } = require('../models');

const equipmentData = [
    {
        asset_name: 'Apple iPad (10th Generation)',
        serial_num: 'DLXR60W0GHK9',
        price: 399.99,
        link: 'https://www.amazon.com/Apple-2022-10-9-inch-iPad-Wi-Fi/dp/B0BJLXMVMV/ref=sr_1_4',
        is_checked_out: true,
    },
    {
        asset_name: 'Apple iPad (9th Generation)',
        serial_num: 'DMPR3NRVFK10',
        price: 399.99,
        link: 'https://www.amazon.com/2021-Apple-10-2-inch-iPad-Wi-Fi/dp/B09G9CJM1Z/ref=sr_1_3',
        is_checked_out: true,
    },
    {
        asset_name: 'Apple iPad (9th Generation)',
        serial_num: 'DMPUEN48FK11',
        price: 399.99,
        link: 'https://www.amazon.com/2021-Apple-10-2-inch-iPad-Wi-Fi/dp/B09G9CJM1Z/ref=sr_1_3',
        is_checked_out: false,
    },
    {
        asset_name: 'Apple iPad (10th Generation)',
        serial_num: 'DMH4KC9FK14',
        price: 399.99,
        link: 'https://www.amazon.com/Apple-2022-10-9-inch-iPad-Wi-Fi/dp/B0BJLXMVMV/ref=sr_1_4',
        is_checked_out: true,
    },
    {
        asset_name: 'Apple iPad (10th Generation)',
        serial_num: 'DJ30CH58K14',
        price: 399.99,
        link: 'https://www.amazon.com/Apple-2022-10-9-inch-iPad-Wi-Fi/dp/B0BJLXMVMV/ref=sr_1_4',
        is_checked_out: true,
    },
    {
        asset_name: 'Apple iPad (10th Generation)',
        serial_num: 'DMPR5SV9FK14',
        price: 399.99,
        link: 'https://www.amazon.com/Apple-2022-10-9-inch-iPad-Wi-Fi/dp/B0BJLXMVMV/ref=sr_1_4',
        is_checked_out: true,
    },
    {
        asset_name: 'HP 14-inch Chromebook HD Touchscreen',
        serial_num: 'C0764MNCG832JF',
        price: 234.00,
        link: 'https://www.amazon.com/HP-14-inch-Chromebook-Touchscreen-Bluetooth/dp/B07L52KX7B/ref=sr_1_6',
        is_checked_out: true,
    },
    {
        asset_name: 'HP 14-inch Chromebook HD Touchscreen',
        serial_num: 'C0Y4K29CJ382JF',
        price: 234.00,
        link: 'https://www.amazon.com/HP-14-inch-Chromebook-Touchscreen-Bluetooth/dp/B07L52KX7B/ref=sr_1_6',
        is_checked_out: true,
    },
    {
        asset_name: 'HP 14-inch Chromebook HD Touchscreen',
        serial_num: 'C0Y4KCJ3K592JX',
        price: 234.00,
        link: 'https://www.amazon.com/HP-14-inch-Chromebook-Touchscreen-Bluetooth/dp/B07L52KX7B/ref=sr_1_6',
        is_checked_out: false,
    },
    {
        asset_name: 'C Pen Text to Speech Reader 2',
        serial_num: 'C87N392',
        price: 295.00,
        link: 'https://www.amazon.com/Pen-Text-Speech-Reader-Differences/dp/B0BGPNM5B4/ref=sr_1_3',
        is_checked_out: true,
    },
    {
        asset_name: 'C Pen Text to Speech Reader 2',
        serial_num: 'X87N397',
        price: 295.00,
        link: 'https://www.amazon.com/Pen-Text-Speech-Reader-Differences/dp/B0BGPNM5B4/ref=sr_1_3',
        is_checked_out: true,
    },
    {
        asset_name: 'C Pen Text to Speech Reader 2',
        serial_num: 'X87N482',
        price: 295.00,
        link: 'https://www.amazon.com/Pen-Text-Speech-Reader-Differences/dp/B0BGPNM5B4/ref=sr_1_3',
        is_checked_out: false,
    },
    {
        asset_name: 'Cetacea Sound Astronaut CL Soundfield',
        serial_num: 'DTE3926FK39XK',
        price: 779.00,
        link: 'https://www.amazon.com/Astronaut-CL-Soundfield-Wireless-Amplification/dp/B07PP4C2RD/ref=sr_1_3',
        is_checked_out: true,
    },
    {
        asset_name: 'Cetacea Sound Astronaut CL Soundfield',
        serial_num: 'DTE3926FK48HD',
        price: 779.00,
        link: 'https://www.amazon.com/Astronaut-CL-Soundfield-Wireless-Amplification/dp/B07PP4C2RD/ref=sr_1_3',
        is_checked_out: false,
    },
    {
        asset_name: 'Microsoft Surface Pro 9',
        serial_num: 'J98DCH38DHJ89',
        price: 830.89,
        link: 'https://www.amazon.com/Microsoft-Lightweight-Processor-Multi-Tasking-Platinum/dp/B0B9Q2ZB5T?ref_=ast_sto_dp&th=1',
        is_checked_out: true,
    },
    {
        asset_name: 'Microsoft Surface Pro 9',
        serial_num: 'J98DCH38DHJ89',
        price: 830.89,
        link: 'https://www.amazon.com/Microsoft-Lightweight-Processor-Multi-Tasking-Platinum/dp/B0B9Q2ZB5T?ref_=ast_sto_dp&th=1',
        is_checked_out: false,
    },
    {
        asset_name: 'Microsoft Surface Pro 9',
        serial_num: 'J98DCH38DHJ89',
        price: 830.89,
        link: 'https://www.amazon.com/Microsoft-Lightweight-Processor-Multi-Tasking-Platinum/dp/B0B9Q2ZB5T?ref_=ast_sto_dp&th=1',
        is_checked_out: false,
    },
    {
        asset_name: 'Microsoft Surface Pro 9',
        serial_num: 'J98DCH38DHJ89',
        price: 830.89,
        link: 'https://www.amazon.com/Microsoft-Lightweight-Processor-Multi-Tasking-Platinum/dp/B0B9Q2ZB5T?ref_=ast_sto_dp&th=1',
        is_checked_out: false,
    },
    {
        asset_name: 'Microsoft Surface Pro 9',
        serial_num: 'J98DCH38DHJ89',
        price: 830.89,
        link: 'https://www.amazon.com/Microsoft-Lightweight-Processor-Multi-Tasking-Platinum/dp/B0B9Q2ZB5T?ref_=ast_sto_dp&th=1',
        is_checked_out: false,
    },
    {
        asset_name: 'Microsoft Surface Pro 9',
        serial_num: 'J98DCH38DHJ89',
        price: 830.89,
        link: 'https://www.amazon.com/Microsoft-Lightweight-Processor-Multi-Tasking-Platinum/dp/B0B9Q2ZB5T?ref_=ast_sto_dp&th=1',
        is_checked_out: false,
    },
    {
        asset_name: 'TouchChat Communication App',
        serial_num: '',
        price: 830.89,
        link: 'https://www.amazon.com/Microsoft-Lightweight-Processor-Multi-Tasking-Platinum/dp/B0B9Q2ZB5T?ref_=ast_sto_dp&th=1',
        is_checked_out: false,
    },
];

const seedEquipment = () => Equipment.bulkCreate(equipmentData);

module.exports = seedEquipment;
